#!/bin/bash
#apache paigaldus skriptiga
#kontrollime, kas apache2 on paigaldatud
APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")
#kui ridade arv on 0: pole apache2 paigaldatud ja tuleb paigaldada
if [ $APACHE2 -eq 0 ]; then
	echo "Paigaldame apache2"
	sudo apt-get install apache2;
#kui ridade arv on 1: siis on apache2 paigaldatud
elif [ $APACHE2 -eq 1 ]; then
	echo "apache2 on paigaldatud!"
	#kuvab apache2 staatust, kas toimib/ei toimi
	service apache2 status
fi
